# -*- coding: utf-8 -*-
"""Punto 4 Taller 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORA2oI8eKCdaow_T9FYt1hX5N5yOMagf
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import pandas as pd

Datos=pd.read_csv('OGLE-LMC-CEP-0001.dat', sep=" ", header=None)
Datos.columns=["Tiempo", "Brillo", "Delta brillo"]
Datos

plt.scatter(Datos["Tiempo"], Datos["Brillo"], color="teal")

def Fourier_transfrom(t,y,f):
  T=[]
  for i in range(len(f)):
    transformados=(y*(np.exp((-1*2*np.pi*f[i]*t)*1j))).sum()
    T.append(transformados)
  return np.array(T)

tiempos=np.array(Datos["Tiempo"])
brillo=np.array(Datos["Brillo"])

frequ=np.linspace(0.1, 2, 300)
F0=Fourier_transfrom(tiempos, brillo, frequ)
plt.plot(frequ, abs(F0), color="yellowgreen")
picon=np.where(abs(F0)==abs(F0).max())
plt.scatter(frequ[picon], abs(F0)[picon], color="green")
frecuencia_imp0=frequ[picon]
print("La frecuencia de la señal es: "+ str(frecuencia_imp0))

general=np.linspace(5263, 7495, 7495-5263+1)
Tnuevos=[]
Bnuevos=[]
for i in range(len(general)):
  if general[i] in np.round(tiempos,0):
    w=np.where(np.round(tiempos,0)==general[i])
    Tnuevos.append(round(tiempos[w][0],0))
    Bnuevos.append(brillo[w][0])
  else:
    Tnuevos.append(round(general[i],0))
    Bnuevos.append(np.mean(brillo))
Tnuevos=np.array(Tnuevos)
Bnuevos=np.array(Bnuevos)
plt.scatter(Tnuevos, Bnuevos, color="navy")

ny=(len(general)/(7495-5263))/2
frecuencias2=np.linspace(0.1,ny*3, len(Tnuevos))

Fi=Fourier_transfrom(Tnuevos, Bnuevos, frecuencias2)
plt.plot(frecuencias2, abs(Fi), color="yellowgreen")
pico=np.where(abs(Fi)==abs(Fi[800:]).max())
plt.scatter(frecuencias2[pico], abs(Fi)[pico], color="green")
frecuencia_imp=frecuencias2[pico]
print("La frecuencia de la señal es: "+ str(frecuencia_imp))

phi = np.mod(frecuencia_imp*brillo,1)
plt.scatter(phi,brillo, color="orange")
plt.plot(phi,brillo, color="orange")
plt.xlabel("ϕ (fase)")
plt.ylabel("Brillo")
plt.title("Comparación de brillo con su fase")
plt.savefig("4.pdf")